fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    rabbitmq: "https://github.com/puppetlabs/puppetlabs-rabbitmq.git"
 
# default module layout

  symlinks:
    demo_mco_middleware: "#{source_dir}"
