fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    rabbitmq: "https://github.com/puppetlabs/puppetlabs-rabbitmq.git"
    apt: "git://github.com/puppetlabs/puppetlabs-apt.git"
    staging: "git://github.com/voxpupuli/puppet-staging.git"
    erlang: "git://github.com/garethr/garethr-erlang.git"
 
# default module layout

  symlinks:
    demo_mco_middleware: "#{source_dir}"
